Update integration-test.yaml

diff --git a/.github/workflows/integration-test.yaml b/.github/workflows/integration-test.yaml
--- a/.github/workflows/integration-test.yaml
+++ b/.github/workflows/integration-test.yaml
@@ -50,6 +50,7 @@ jobs:
           # Request to fetch simulation types
           response=$(curl -sX GET http://localhost:${ADAPTOR_MANAGER_PORT}/simulation/type)
           echo "$response"
+          
           # Verify the response contains "availableSimulations" array with specified entries
           echo "$response" | jq '.availableSimulations' | grep -q 'DEMO' || exit 1
           echo "$response" | jq '.availableSimulations' | grep -q 'WEBOTS' || exit 1
@@ -61,12 +62,14 @@ jobs:
             -d '{"simulationType": "WEBOTS", "instanceId": "MY_PERSONAL_WEBOTS_INSTANCE", "instanceHost": "127.0.0.1", "instancePort": 10010}' \
             http://localhost:${ADAPTOR_MANAGER_PORT}/simulation/instance
           echo "Adding simulation instance (demo)"
+          
           # Request to manager endpoint to add a DEMO instance
           curl -sX POST \
             -H "Content-Type: application/json" \
             -d '{"simulationType": "DEMO", "instanceId": "MY_PERSONAL_DEMO_INSTANCE", "instanceHost": "127.0.0.1", "instancePort": 10011}' \
             http://localhost:${ADAPTOR_MANAGER_PORT}/simulation/instance
           echo "Fetching simulation instances to verify registration of instances"
+          
           # Request to fetch simulation instances
           response=$(curl -sX GET http://localhost:${ADAPTOR_MANAGER_PORT}/simulation/instance)
           echo "$response"
@@ -74,7 +77,50 @@ jobs:
           # Verify the response is an array with exactly two entries
           echo "$response" | jq 'length' | grep -q '^2$' || exit 1
           
-      - name: Trigger update of e2e test-completion time in gh-pages
+          # Request to initialize a session
+          response=$(curl -sX 'POST' \
+                'http://localhost:${ADAPTOR_MANAGER_PORT}/session' \
+                -H 'accept: application/json' \
+                -H 'Content-Type: application/json' \
+                -d '{"type": "ANY","n": 2}')
+          echo "$response"
+
+          # Verify both simulations are contained in session
+          echo "$response" | jq '.acquiredSimulations' | grep -q 'DEMO' || exit 1
+          echo "$response" | jq '.acquiredSimulations' | grep -q 'WEBOTS' || exit 1
+
+          # Extract session-key
+          sessionKey=$(echo "$response" | jq -r '.sessionKey')
+
+          # send set-joint-position command
+          executionId = $(curl -X 'POST' \
+            'http://localhost:${ADAPTOR_MANAGER_PORT}/session/${sessionKey}' \
+            -H 'accept: text/html' \
+            -H 'Content-Type: application/json' \
+            -d '{"type": "SET_JOINT_POSITION","jointPosition": {"joint": "AXIS_1","radians": 1}}')
+          
+          # wait a bit
+          sleep 5s
+
+          # request execution response
+          response=$(curl -X 'GET' 'http://localhost:${ADAPTOR_MANAGER_PORT}/session/execution/${executionId}' -H 'accept: application/json')
+
+          # verify responses from simulations
+          # Use jq to extract status codes for DEMO and WEBOTS
+          demoStatusCode=$(echo "$response" | jq -r '.responses[] | select(.simulationName == "DEMO") .responseCode')
+          webotsStatusCode=$(echo "$response" | jq -r '.responses[] | select(.simulationName == "WEBOTS") .responseCode')
+          echo ${demoStatusCode}
+          echo ${webotsStatusCode}
+          
+          # Verify the status codes
+          if [ "$demoStatusCode" = "200" ] && [ "$webotsStatusCode" = "500" ]; then
+            echo "Verification successful!"
+          else
+            echo "Verification failed!"
+            exit 1
+          fi
+          
+      - name: Trigger update of test-completion time in gh-pages
         if: success() # Ensure this runs only if the previous steps were successful
         run: |
           curl -X POST \
