Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,8 +34,13 @@ jobs:
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add .env
+
+          # Check for changes
           git diff --staged --exit-code
-          if [ $? -eq 1 ]; then
+          CHANGES=$?
+
+          # If there are changes (exit code 1), commit them
+          if [ $CHANGES -eq 1 ]; then
             git commit -m "Update Docker image tags to $NEW_TAG"
             git push
           else
